# -----------------------------
# Builder Stage
# -----------------------------
FROM node:22-slim AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build


# -----------------------------
# Runner Stage
# -----------------------------
FROM gcr.io/distroless/nodejs22-debian12

WORKDIR /app

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000

CMD ["server.js"]