version: '3.8'

services:

  backend:
    container_name: questly-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: kumar3472/questly-backend:latest
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    networks:
      - qnet
    restart: unless-stopped

  frontend:
    container_name: questly-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: kumar3472/questly-frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - qnet
    restart: unless-stopped

networks:
  qnet:
    name: qnet